name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  built:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: app
        submodules: recursive
    - name: initialize
      working-directory: app
      run: |
        pip3 install -U west
        west init -l
        west update
        west zephyr-export
        pip3 install -r ../zephyr/scripts/requirements.txt
        ls ../
        ls ../../
    - name: build
      working-directory: app
      run: |
        west build . -- -DBUILD_ENV=prod
        mkdir -p build-out
        cp build/zephyr/zephyr.bin build-out/tv-bench-ctrl-firm_update_${{ GITHUB_REF }}.bin
        cp build/zephyr/zephyr.hex build-out/tv-bench-ctrl-firm_hex_${{ GITHUB_REF }}.hex
        cp build/zephyr/zephyr.hex build-out/tv-bench-ctrl-firm_elf_${{ GITHUB_REF }}.elf
    - name: upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tv-bench-crl-frim-builds
        path: app/build-out/
