name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: app
        submodules: recursive
    - name: initialize
      working-directory: app
      run: |
        pip3 install -U west
        west init -l
        west update
        pip3 install -r ../zephyr/scripts/requirements.txt
    - name: tests
      working-directory: app
      run: zephyr/scripts/twister -T .
    - name: upload results
      working-directory: app
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tv-bench-crl-frim-test-results
        path: ../twister-out/
