name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: tests
      uses: docker://judebake/electronya-firm-builder:3.2.0
      with:
        args: test
      env:
        CMAKE_PREFIX_PATH: /opt/toolchains/zephyr-sdk-0.16.0/
        ZEPHYR_DIR: /zephyr-project/zephyr/share/zephyr-package/cmake/
        ZEPHYR_SDK_DIR: /opt/toolchains/zephyr-sdk-0.16.0/cmake/
    - name: upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tv-bench-crl-frim-test-results
        path: twister-out/
