name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: tests
      run: ./scripts/build.sh -m test
    - name: upload results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: tv-bench-crl-frim-test-results
        path: twister-out/
