name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: tests
      uses: docker://judebake/electronya-firm-builder:3.2.0
      with:
        args: test
      env:
        CMAKE_PREFIX_PATH: /opt/toolchains
        # ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.13.2
        # ZEPHYR_BASE: /zephyr-project/zephyr
        # CLANG_ROOT_DIR: /usr/lib/llvm-12
    - name: upload results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: tv-bench-crl-frim-test-results
        path: twister-out/
