name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://judebake/electronya-firm-builder:3.2.0
      volumes:
        - ${{ github.workspace }}:/zephyr-project/app
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: tests
      run: ../entrypoint.sh test
    - name: upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tv-bench-crl-frim-test-results
        path: twister-out/
