name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: app
        submodules: recursive
    - name: initialize
      working-directory: app
      run: |
        pip3 install -U west
        west init -l
        west update
        west zephyr-export
        pip3 install -r ../zephyr/scripts/requirements.txt
        ls ../
        ls ../../
    - name: tests
      working-directory: app
      run: ../zephyr/scripts/twister -W -T .
    # - name: upload results
    #   uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: tv-bench-crl-frim-test-results
    #     path: ../twister-out/
